# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 02 Jun 2013 07:39:41 +0000
*               @ALL          1
*               @user         8
