<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: gabrielkim
 * Date: Fri, 07 Jun 2013 22:01:27 +0900
 */

$conf['title'] = '{Geek & Fuck}, Sweet-Ass.';
$conf['lang'] = 'ko';
$conf['template'] = 'dokuwiki-template-typo-master';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['rememberme'] = 0;
$conf['disableactions'] = 'backlink,index,recent,revisions,source,export_raw';
$conf['rss_type'] = 'rss2';
$conf['userewrite'] = '2';
$conf['canonical'] = 1;
$conf['send404'] = 1;
$conf['plugin']['blog']['formposition'] = 'top';
$conf['plugin']['bookcreator']['toolbar'] = 'always';
$conf['plugin']['bookcreator']['skip_ids'] = '';
$conf['plugin']['disqus']['devel'] = 1;
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox,reverse,showname,showtitle';
$conf['plugin']['mathjax']['config'] = 'MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ["$","$"], ["\\\\(","\\\\)"] ],
        displayMath: [ ["$$","$$"], ["\\\\[","\\\\]"] ],
        processEscapes: true
    }
});';
$conf['plugin']['syntaxhighlighter3']['theme'] = 'shThemeEmacs.css';
$conf['plugin']['tag']['toolbar_icon'] = 1;
$conf['plugin']['aceeditor']['colortheme'] = 'chrome';

// end auto-generated content
